name: CI - Test and promote to early

on:
    push:
        branches:
            - main
permissions:
    contents: write
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
            
            - name: Run tests
              run: mvn test
              
            - name: Merge main into early
              if: success()
              run: |
                 git config user.name "github-actions"
                 git config user.email "github-actions@github.com"
                 git fetch origin
                 git checkout early
                 git merge main
                 git push origin early